# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 01:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('spotify_id', models.CharField(max_length=255)),
                ('uri', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255)),
                ('spotify_id', models.CharField(max_length=255)),
                ('active_track', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='restapi.Track')),
                ('following', models.ManyToManyField(blank=True, related_name='followers', to='restapi.User')),
            ],
        ),
    ]
